'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const R=require('../web/runtime.js');
const hit=(extra={})=>({id:'r',time:10,check:'attack',action:'Atak',target_name:'Szczur',roll:15,rolls:[15],bonus:5,total:20,defense:12,hit:true,damage_dice:'1k8+3',damage_sides:8,damage_rolls:[6],damage_modifier:3,damage:9,...extra});
const savage=(extra={})=>hit({savage_attacker:true,savage_damage_rolls:[[2],[6]],savage_chosen:1,...extra});
test('requested example includes the die and numeric damage, not an unevaluated formula',()=>{
 const r=savage(),text=R.combatSummary(r);assert.match(text,/Rzut 1: 1k8 = 2/);assert.match(text,/Rzut 2: 1k8 = 6 ✓ wybrany/);assert.match(text,/Obrażenia: 6 \+ 3 → 9/);assert.doesNotMatch(text,/Obrażenia: 1k8/);
});
test('ordinary weapon uses the same sequence',()=>{assert.deepEqual(R.damageRollLines(hit()),['Rzut: 1k8 = 6','Obrażenia: 6 + 3 → 9']);});
test('multiple dice show their actual faces and subtotal',()=>{assert.deepEqual(R.damageRollLines(hit({damage_dice:'2k6+3',damage_sides:6,damage_rolls:[2,5],damage:10})),['Rzut: 2k6 = 2 + 5 = 7','Obrażenia: 7 + 3 → 10']);});
test('critical uses the actual number of dice, modifier only once',()=>{const r=savage({critical:true,savage_damage_rolls:[[2,3],[6,4]],damage_rolls:[6,4],damage:13});assert.match(R.savageAttackSummary(r),/Rzut 2: 2k8 = 6 \+ 4 = 10 ✓ wybrany/);assert.deepEqual(R.damageRollLines(r,true),['Obrażenia: 10 + 3 → 13']);});
test('first wins and tied values keep the server selection',()=>{for(const d of [[[7],[2]],[[4],[4]]]){const text=R.savageAttackSummary(savage({savage_damage_rolls:d,savage_chosen:0}));assert.match(text,/Rzut 1: 1k8 = [47] ✓ wybrany/);assert.equal(text.match(/wybrany/g).length,1);}});
test('all k20 checks show dice and numeric arithmetic',()=>{for(const check of ['attack','save','ability','escape','concentration']){const lines=R.checkRollLines(hit({check,saved:true})).join(' · ');assert.match(lines,/1k20 = 15/);assert.match(lines,/15 \+ 5 → 20/);assert.match(lines,check==='attack'?/KP 12/:/ST 12/);}});
test('negative bonuses are subtraction, never plus-minus',()=>{assert.match(R.checkRollLines(hit({bonus:-2,total:13})).join(' · '),/15 − 2 → 13/);assert.deepEqual(R.damageRollLines(hit({damage_modifier:-2,damage:4})),['Rzut: 1k8 = 6','Obrażenia: 6 − 2 → 4']);});
test('advantage, disadvantage and ties mark the selected recorded face',()=>{for(const [roll,dis,adv]of [[4,true,false],[16,false,true]]){const text=R.checkRollLines(hit({rolls:[4,16],roll,total:roll+5,disadvantage:dis,advantage:adv})).join(' · ');assert.match(text,new RegExp(`1k20 = ${roll} ✓ wybrany`));assert.equal(text.match(/wybrany/g).length,1);}});
test('automatic failures and wards do not invent k20 zero or undefined',()=>{const fail=R.checkRollLines({check:'save',automatic_failure:true,roll:0,rolls:[]});assert.deepEqual(fail,['Obrona: automatyczne niepowodzenie']);assert.doesNotMatch(R.combatSummary({id:1,check:'ward',absorbed:7}),/k20|undefined|NaN/);});
test('lucky shows the second actual d20 and selected total',()=>{const text=R.checkRollLines(hit({check:'concentration',rolls:[3],roll:17,total:22,saved:true,lucky:true,lucky_previous:3,lucky_roll:17})).join(' · ');assert.match(text,/Rzut: 1k20 = 3/);assert.match(text,/Szczęściarz: 1k20 = 17 ✓ wybrany/);assert.match(text,/17 \+ 5 → 22/);});
test('Guidance and Precision dice are separate from the fixed bonus',()=>{const text=R.checkRollLines(hit({check:'ability',bonus:8,total:23,saved:true,check_extra_rolls:[{name:'Wskazówki',sides:4,rolls:[3],sign:1}]})).join(' · ');assert.match(text,/Wskazówki: 1k4 = 3/);assert.match(text,/15 \+ 5 \+ 3 → 23/);});
test('negative Omen is subtracted once',()=>{const text=R.checkRollLines(hit({bonus:2,total:17,check_extra_rolls:[{name:'Kosmiczny omen',sides:6,rolls:[3],sign:-1}]})).join(' · ');assert.match(text,/1k6 = 3 \(odejmij\)/);assert.match(text,/15 \+ 5 − 3 → 17/);});
test('missing damage faces never get reconstructed from final damage',()=>{const text=R.combatSummary(hit({damage_rolls:undefined,damage_sides:undefined}));assert.match(text,/Kości: 1k8\+3/);assert.match(text,/Obrażenia: 9 obr/);assert.doesNotMatch(text,/1k8 = 6/);});
test('damage riders are separate dice; modifier is not counted twice',()=>{const r=hit({damage_dice:'1k8+3 + 1k6 (Znak)',damage:13,mark_rolls:[4],extra_damage_rolls:[{name:'Znak łowcy',sides:6,rolls:[4],modifier:0}]});assert.deepEqual(R.damageRollLines(r),['Rzut: 1k8 = 6','Znak łowcy: 1k6 = 4','Obrażenia: 6 + 3 + 4 → 13']);});
test('independent spell dice may use different sides and modifiers',()=>{const r=hit({check:'automatic',damage_sides:6,damage_rolls:[3,4],damage_modifier:0,damage:14,extra_damage_rolls:[{name:'Zimno',sides:8,rolls:[5],modifier:2}]});assert.deepEqual(R.damageRollLines(r),['Rzut: 2k6 = 3 + 4 = 7','Zimno: 1k8 = 5','Obrażenia: 7 + 5 + 2 → 14']);});
test('saved spell and resistance preserve a correct subtotal and the actual final damage',()=>{const r=hit({check:'save',saved:true,save_half:true,damage:4});const lines=R.damageRollLines(r);assert(lines.includes('Obrażenia: 6 + 3 → 9'));assert.match(lines.at(-1),/4 obr/);assert.doesNotMatch(lines.join(' · '),/6 \+ 3 → 4/);});
test('healing shows the rolled amount and separately the HP cap',()=>{assert.deepEqual(R.damageRollLines(hit({check:'healing',healing:4,damage:0})),['Rzut: 1k8 = 6','Leczenie: 6 + 3 → 9','Odzyskano: 4 zdrowia (do pełna)']);});
test('flat heals and fixed damage are not labeled as a die',()=>{assert.deepEqual(R.damageRollLines({check:'healing',damage_dice:'25',damage_rolls:[],healing:25}),['Leczenie: 25']);assert.doesNotMatch(R.combatSummary({id:1,check:'automatic',damage:5,hit:true}),/k20|k8|undefined/);});
test('short rest shows every die, healer reroll and total healing',()=>{const r={check:'healing',healing:7,rest_rolls:[{sides:10,first:1,reroll:6,value:6,modifier:2,potential:8},{sides:10,first:3,reroll:null,value:3,modifier:2,potential:5}]};const s=R.damageRollLines(r).join(' · ');assert.match(s,/Kość 1: 1k10 = 1 · Uzdrowiciel: 1k10 = 6 ✓ wybrany/);assert.match(s,/Leczenie: 8 \+ 5 → 13/);assert.match(s,/Odzyskano: 7/);});
test('style-adjusted dice distinguish rolled faces from applied values',()=>{const r=savage({damage_sides:6,savage_damage_rolls:[[1,6],[4,4]],savage_scored_rolls:[[3,6],[4,4]],savage_chosen:0,damage_rolls:[3,6],raw_damage_rolls:[1,6],damage:12});assert.match(R.savageAttackSummary(r),/2k6 = 1 \+ 6 → 3 \+ 6 = 9 ✓ wybrany/);assert.deepEqual(R.damageRollLines(r,true),['Obrażenia: 9 + 3 → 12']);});
test('piercer reroll and parry die remain explicit',()=>{const r=hit({piercer_reroll:[2,6],parry_roll:3,parry_sides:8,parry_modifier:2,parry_reduction:5,damage:4});const text=R.damageRollLines(r).join(' · ');assert.match(text,/Przebijacz: 1k8 = 2 → 1k8 = 6/);assert.match(text,/Parowanie: 1k8 = 3 · 3 \+ 2 → 5 · blokuje 5/);});
test('falsy damage values and invalid dice cannot render NaN or double signs',()=>{for(const extra of [{damage_rolls:['6']},{damage_rolls:[NaN]},{damage_sides:0},{damage_rolls:[1001]},{damage_rolls:[]}])assert.doesNotMatch(R.combatSummary(hit(extra)),/NaN|undefined|\+ −|\+ -/);});
test('rendering never mutates the authoritative receipt',()=>{const r=savage(),before=JSON.stringify(r);R.combatSummary(r);R.damageRollDetails(r);R.checkRollLines(r);assert.equal(JSON.stringify(r),before);});

test('maximum damage is labeled as a maximum rather than a random throw',()=>{const r=hit({check:'automatic',damage_maximized:true,damage_rolls:[8],damage:11});assert.deepEqual(R.damageRollLines(r),['Maksymalne kości: 1k8 = 8','Obrażenia: 8 + 3 → 11']);});
test('Piercer extra critical die stays visible when Savage Attacker already displays its own sets',()=>{const r=savage({critical:true,savage_damage_rolls:[[2,3],[6,4]],savage_chosen:1,damage_rolls:[6,4,5],piercer_critical:5,damage:18});assert.deepEqual(R.damageRollLines(r,true),['Przebijacz · krytyk: 1k8 = 5','Obrażenia: 15 + 3 → 18']);});

test('a pure dice pool without modifiers does not repeat an identical subtotal',()=>{assert.deepEqual(R.damageRollLines(hit({check:'automatic',damage_sides:6,damage_rolls:[4,4],damage_modifier:0,damage:8})),['Rzut: 2k6 = 4 + 4 = 8','Obrażenia: 8']);});
