/* D&D ability choices, proficiencies and actual checks. All results belong to the server. */
(function(root){'use strict';
 const abilityNames={strength:'Siła',dexterity:'Zręczność',constitution:'Kondycja',intelligence:'Inteligencja',wisdom:'Mądrość',charisma:'Charyzma'};
 const ids=Object.keys(abilityNames),drafts=new Map(),skillPicks=new Map(),asiPicks=new Map();
 const signed=n=>Number(n)>=0?'+'+n:String(n);
 const node=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;};
 const button=(label,fn)=>{const b=node('button','',label);b.type='button';b.onclick=fn;return b;};
 const current=(h,p)=>h.state?.().player||p;
 function choiceReason(p){if(!p?.alive)return 'Wybór po odrodzeniu.';if(p.class_chosen===false)return 'Najpierw wybierz profesję.';if(p.form||p.polymorph)return 'Wybór po zakończeniu przemiany.';if(p.combat_remaining>0)return 'Wybór po zakończeniu walki.';return '';}
 function buildCost(config,scores){if(!scores||ids.some(id=>!Number.isInteger(scores[id])||scores[id]<8||scores[id]>15||!Number.isFinite(Number(config?.costs?.[scores[id]]))))return NaN;return ids.reduce((sum,id)=>sum+Number(config.costs[scores[id]]),0);}
 function buildReason(p,draft){const reason=choiceReason(p),config=p?.character_sheet?.ability_build;if(reason)return reason;if(!config||config.chosen)return 'Cechy początkowe zostały już zatwierdzone.';const cost=buildCost(config,draft?.scores);if(!Number.isFinite(cost))return 'Każda cecha bazowa musi wynosić od 8 do 15.';if(cost!==config.points)return `Wydaj dokładnie ${config.points} punktów na cechy bazowe.`;const bonuses=ids.map(id=>draft?.background?.[id]);if(bonuses.some(v=>!Number.isInteger(v)||v<0||v>2)||bonuses.reduce((a,b)=>a+b,0)!==(config.background_points||3))return 'Premia pochodzenia: +2 i +1 albo +1 do trzech różnych cech.';return '';}
 function trainingPacket(p,feat,fields={}){return {type:'training_feat',feat,...fields,...(Number.isInteger(p.character_sheet?.training?.spent)?{expected_spent:p.character_sheet.training.spent}:{})};}
 function asiReason(p,selected){const reason=choiceReason(p),tr=p?.character_sheet?.training,option=tr?.options?.find(f=>f.id==='ability_score_improvement');if(reason)return reason;if(!(tr?.points>0))return 'Brak dostępnego wyboru rozwoju.';if(!option)return 'Zwiększenie cech jest obecnie niedostępne.';if(!Array.isArray(selected)||selected.length!==2||selected.some(id=>!option.abilities?.includes(id)))return 'Przydziel oba punkty cech.';const gains={};for(const id of selected)gains[id]=(gains[id]||0)+1;if(Object.entries(gains).some(([id,n])=>Number(p.attributes?.[id]||0)+n>(tr.score_cap||20)))return `Cecha nie może przekroczyć ${tr.score_cap||20}.`;return '';}
 function skillReason(p,source,id){const reason=choiceReason(p),pool=p?.character_sheet?.skills?.choices?.find(x=>x.source===source);if(reason)return reason;if(!(pool?.remaining>0))return 'Wszystkie wybory z tej puli zostały wykorzystane.';if(!pool.options?.some(x=>x.id===id))return 'Wybierz dostępną umiejętność.';return '';}
 function challengeReason(p,entry){if(!p?.alive)return 'Próba po odrodzeniu.';if(!entry)return 'To wyzwanie nie jest już w pobliżu.';if(entry.completed&&!entry.repeatable)return 'Wyzwanie ukończone.';if(entry.available!==true)return [entry.reason||'Podejdź bliżej, aby wykonać próbę.',entry.cooldown_remaining>0?`Kolejna próba za ${Math.ceil(entry.cooldown_remaining)} s.`:''].filter(Boolean).join(' ');return '';}
 function getDraft(p){const key=String(p.id),c=p.character_sheet.ability_build;let d=drafts.get(key);if(!d){d={scores:{...(c.initial_scores||Object.fromEntries(ids.map((id,i)=>[id,[15,14,13,12,10,8][i]])))},background:{...Object.fromEntries(ids.map(id=>[id,0])),...(c.initial_background||{strength:2,constitution:1})},open:false};drafts.set(key,d);}return d;}
 function refreshBuild(box,p,d){const c=p.character_sheet?.ability_build||{},cost=buildCost(c,d.scores);box.querySelector('[data-build-budget]').textContent=`Punkty cech: ${Number.isFinite(cost)?cost:'—'} / ${c.points||27} · premia pochodzenia: ${ids.reduce((n,id)=>n+(Number(d.background[id])||0),0)} / ${c.background_points||3}`;for(const row of box.querySelectorAll('[data-build-ability]')){const id=row.dataset.buildAbility,v=Number(d.scores[id])+Number(d.background[id]);row.querySelector('output').textContent=`${v} (${signed(Math.floor((v-10)/2))})`;}
  const reason=buildReason(p,d),b=box.querySelector('[data-build-confirm]');b.disabled=!!reason;b.title=reason;box.querySelector('[data-build-reason]').textContent=reason||'Zatwierdzenie jest jednorazowe. Atuty zdobyte na wyższych poziomach doliczą się osobno.';}
 function abilityBuild(parent,p,h){const c=p.character_sheet?.ability_build;if(!c||c.chosen)return;const d=getDraft(p),box=node('details','sheet-build');box.open=h.initialExpanded||d.open;box.append(node('summary','',`Cechy początkowe · wybierz własny rozkład ${c.points} punktów`));box.addEventListener('toggle',()=>{d.open=box.open;});box.append(node('p','sheet-hint','Możesz jednorazowo zastąpić domyślne cechy profesji. Baza: 8–15. Premia pochodzenia: +2 i +1 albo trzy razy +1.'));
  const budget=node('strong','sheet-build-budget');budget.dataset.buildBudget='';box.append(budget);const grid=node('div','sheet-build-grid');
  for(const id of ids){const row=node('div','sheet-build-row');row.dataset.buildAbility=id;row.append(node('strong','',abilityNames[id]));for(const [kind,label]of [['scores','Baza'],['background','Pochodzenie']]){const wrap=node('label'),select=node('select');select.setAttribute('aria-label',`${abilityNames[id]} · ${label}`);for(let n=kind==='scores'?8:0;n<=(kind==='scores'?15:2);n++)select.append(new Option(kind==='scores'?`${n} · koszt ${c.costs[n]}`:`+${n}`,String(n)));select.value=String(d[kind][id]);select.addEventListener('change',()=>{d[kind][id]=Number(select.value);refreshBuild(box,current(h,p),d);});wrap.append(node('small','',label),select);row.append(wrap);}row.append(node('output'));grid.append(row);}box.append(grid);
  const hint=node('p','sheet-choice-reason');hint.dataset.buildReason='';const confirm=button('Zatwierdź cechy na stałe',()=>{const latest=current(h,p);if(!buildReason(latest,d)){confirm.disabled=true;h.send({type:'ability_build',scores:{...d.scores},background:{...d.background}});}});confirm.dataset.buildConfirm='';box.append(hint,confirm);parent.append(box);refreshBuild(box,p,d);
 }
 function advancement(parent,p,h){const tr=p.character_sheet?.training;if(!tr)return;const box=node('section','sheet-advancement');box.append(node('h3','',`Rozwój cech i atutów · wybory: ${tr.points||0}`));
  const next=(tr.levels||[]).find(n=>n>p.level);box.append(node('p','sheet-hint',`Jeden wybór daje +2 do jednej cechy, +1 do dwóch cech albo jeden atut. Limit cechy: ${tr.score_cap||20}.${next?` Kolejny wybór: poziom ${next}.`:''}`));if(tr.migration_notice)box.append(node('p','sheet-hint',tr.migration_notice));
  if(tr.points>0){const option=tr.options?.find(f=>f.id==='ability_score_improvement');if(option){const key=String(p.id),saved=asiPicks.get(key),eligible=option.abilities||[],selected=saved||[eligible[0],eligible.find(id=>id!==eligible[0])||eligible[0]];asiPicks.set(key,selected);const controls=node('div','sheet-asi-controls');for(let i=0;i<2;i++){const label=node('label'),select=node('select');label.append(node('small','',`Punkt cechy ${i+1}`));select.setAttribute('aria-label',`Rozwój cech · punkt ${i+1}`);for(const id of eligible)select.append(new Option('+1 '+(abilityNames[id]||id),id));select.value=selected[i]||'';select.addEventListener('change',()=>{selected[i]=select.value;syncAdvancement(box,current(h,p));});label.append(select);controls.append(label);}const confirm=button('Zwiększ cechy',()=>{const latest=current(h,p),choices=asiPicks.get(key);if(!asiReason(latest,choices)){confirm.disabled=true;h.send(trainingPacket(latest,'ability_score_improvement',{abilities:[...choices]}));}});confirm.dataset.asiConfirm='';controls.append(confirm);box.append(controls);const reason=node('p','sheet-choice-reason');reason.dataset.asiReason='';box.append(reason);}
   box.append(button('Poznaj atuty zamiast zwiększania cech',()=>h.open?.('feats')));
  }else box.append(node('small','',`Poziomy rozwoju tej profesji: ${(tr.levels||[]).join(', ')}.`));parent.append(box);syncAdvancement(box,p);
 }
 function syncAdvancement(parent,p){const b=parent.querySelector('[data-asi-confirm]');if(!b)return;const choices=asiPicks.get(String(p.id)),reason=asiReason(p,choices);b.disabled=!!reason;b.title=reason;const summary={};for(const id of choices||[])summary[id]=(summary[id]||0)+1;parent.querySelector('[data-asi-reason]').textContent=reason||Object.entries(summary).map(([id,n])=>`${abilityNames[id]}: ${p.attributes?.[id]} → ${Number(p.attributes?.[id]||0)+n}`).join(' · ');}
 function originReason(p,id){const why=choiceReason(p),origin=p?.character_sheet?.training?.origin;if(why)return why;if(!origin||origin.chosen||!(origin.points>0))return 'Atut pochodzenia został już wybrany.';if(!origin.options?.some(o=>o.id===id))return 'Ten atut nie jest dostępny.';return '';}
 function origin(parent,p,h){const o=p.character_sheet?.training?.origin;if(!o)return;const box=node('section','sheet-advancement');
  if(o.chosen){box.append(node('h3','','Pierwszy atut · '+o.chosen.name),node('p','sheet-hint',o.chosen.description));}
  else if(o.points>0){box.append(node('h3','','Pierwszy atut · od poziomu 1'),node('p','sheet-hint','Masz jeden bezpłatny wybór. Nie zużywa on późniejszych wyborów cech lub atutów.'),button('Wybierz pierwszy atut',()=>root.BractwoFeatUI.open('origin',current(h,p),h)));}
  else return;parent.append(box);}

 function abilities(parent,p,h){advancement(parent,p,h);abilityBuild(parent,p,h);origin(parent,p,h);sync(parent,p,h);}
 function challenges(parent,p,h){const data=h.state?.().skill_challenges||{},box=node('section','sheet-challenges');box.append(node('h3','sheet-section-title',`Wyzwania w pobliżu · ukończone ${data.completed_count||0}/${data.total||0}`));const entries=[...(data.nearby||[])].sort((a,b)=>Number(a.completed)-Number(b.completed)||a.distance-b.distance);if(!entries.length)box.append(node('p','sheet-hint','Wędruj i wypatruj złotych znaków kości w świecie. Podejdź do takiego miejsca i naciśnij E lub przycisk interakcji.'));
  for(const e of entries){const row=node('article','sheet-challenge'+(e.completed?' completed':''));row.dataset.skillChallenge=e.id;const skill=p.character_sheet?.skills?.skills?.find(s=>s.id===e.skill),head=node('div','sheet-section-row');head.append(node('strong','',e.name),node('span','sheet-skill-bonus',`ST ${e.dc}`));row.append(head,node('p','',e.description),node('small','',`${skill?.name||e.skill} · 1k20${signed(skill?.bonus||0)} · ${Math.ceil(e.distance/32)} pól od ciebie${e.min_level>1?' · poziom '+e.min_level:''}`));if(e.reward_hint)row.append(node('small','sheet-challenge-reward',e.reward_hint));const reason=node('p','sheet-choice-reason');reason.dataset.challengeReason='';const use=button(e.completed?(e.repeatable?'Skorzystaj z przejścia':'Ukończono'):'Wykonaj próbę',()=>{const latest=current(h,p),fresh=h.state?.().skill_challenges?.nearby?.find(x=>x.id===e.id);if(!challengeReason(latest,fresh)){use.disabled=true;h.send({type:'skill_challenge',challenge_id:e.id});}});use.dataset.challengeConfirm=e.id;row.append(reason,use);if(e.completed&&e.result)row.append(node('p','sheet-hint',e.result));if(h.navigate&&(!e.completed||e.repeatable))row.append(button('Wyznacz kierunek',()=>h.navigate(e)));box.append(row);}parent.append(box);
 }
 function skills(parent,p,h,section='list'){const s=p.character_sheet?.skills;if(!s){parent.append(node('p','sheet-hint','Oczekiwanie na umiejętności postaci…'));return;}const summary=node('div','sheet-skill-intro');summary.append(node('h3','',`Umiejętności · premia z biegłości ${signed(s.proficiency_bonus)}`),node('p','sheet-hint',s.description||'Test umiejętności: 1k20 + modyfikator cechy + biegłość, jeśli ją posiadasz. Ekspertyza podwaja premię z biegłości.'));if(section==='list')summary.append(button('Pokaż wyzwania w pobliżu',()=>h.open?.('skills','challenges')));const expertise=s.choices?.find(pool=>pool.source==='expertise');if(section==='training'&&expertise&&!(expertise.remaining>0))summary.append(node('p','sheet-hint',expertise.description));parent.append(summary);
  if(section==='list'&&p.environment?.hide){const box=node('section','sheet-skill-choice'),b=button('',()=>{const latest=current(h,p),hide=latest.environment?.hide;if(latest.alive&&(hide?.active||hide?.available)){b.disabled=true;h.send({type:'environment_action',action:hide.active?'unhide':'hide'});}});b.dataset.hideAction='';box.append(node('strong','','Skradanie się przed potworami'),node('p','sheet-hint','Ukryj się przy osłonie lub we mgle. Test Zręczności (Skradanie), ST 15. Ukrycie działa na potwory; inni gracze nadal cię widzą.'),b);const reason=node('p','sheet-choice-reason');reason.dataset.hideReason='';box.append(reason);parent.append(box);}
  const roll=p.last_roll;if(section==='challenges'&&roll?.check==='ability'){const skill=s.skills?.find(x=>x.id===roll.skill);parent.append(node('p','sheet-hint',`Ostatni test · ${skill?.name||abilityNames[roll.ability]||'Umiejętność'}: ${roll.roll}${signed(roll.bonus)} = ${roll.total} przeciw ST ${roll.defense} · ${roll.saved?'sukces':'niepowodzenie'}.`));}
  if(section==='training'){let pending=0;for(const pool of s.choices||[]){if(!(pool.remaining>0))continue;pending+=pool.remaining;const box=node('section','sheet-skill-choice');box.dataset.skillSource=pool.source;box.append(node('strong','',`${pool.name} · pozostało ${pool.remaining}/${pool.total}`),node('p','sheet-hint',pool.description));const key=String(p.id)+':'+pool.source,select=node('select'),controls=node('div','sheet-skill-choice-controls');select.setAttribute('aria-label',pool.name);select.append(new Option('Wybierz umiejętność…',''));for(const item of pool.options||[])select.append(new Option(`${item.name} · ${item.ability_name}`,item.id));select.value=skillPicks.get(key)||'';select.addEventListener('change',()=>{skillPicks.set(key,select.value);sync(parent,current(h,p),h);});const confirm=button(pool.source==='expertise'?'Wybierz ekspertyzę':'Wybierz biegłość',()=>{const latest=current(h,p),id=skillPicks.get(key);if(!skillReason(latest,pool.source,id)){confirm.disabled=true;h.send({type:'skill_train',source:pool.source,skill_id:id});}});confirm.dataset.skillConfirm=pool.source;const reason=node('p','sheet-choice-reason');reason.dataset.skillReason='';controls.append(select,confirm);box.append(controls,reason);parent.append(box);}if(!pending)parent.append(node('p','sheet-hint','Wszystkie dostępne biegłości zostały wybrane. Atut Wszechstronny pozwala nauczyć się trzech kolejnych.'));}
  if(section==='list'){const grid=node('div','sheet-skill-grid');for(const skill of s.skills||[]){const row=node('article','sheet-skill'+(skill.expertise?' expert':skill.proficient?' proficient':''));row.dataset.skill=skill.id;const head=node('div','sheet-skill-head');head.append(node('strong','',skill.name),node('b','sheet-skill-bonus',signed(skill.bonus)));row.append(head,node('small','sheet-skill-state',`${skill.ability_name} · ${skill.expertise?'Ekspertyza':skill.proficient?'Biegłość':'Bez biegłości'}`),node('p','',skill.description));if(skill.sources?.length)row.append(node('small','',skill.sources.join(' · ')));if(skill.id==='perception')row.append(node('small','',`Pasywna Percepcja: ${skill.passive}`));grid.append(row);}parent.append(grid);}if(section==='challenges')challenges(parent,p,h);sync(parent,p,h);
 }
 function sync(parent,p,h){syncAdvancement(parent,p);const build=parent.querySelector('.sheet-build');if(build&&p.character_sheet?.ability_build)refreshBuild(build,p,getDraft(p));for(const b of parent.querySelectorAll('[data-hide-action]')){const hide=p.environment?.hide;b.disabled=!p.alive||!(hide?.active||hide?.available);b.textContent=hide?.active?'Wyjdź z ukrycia':'Ukryj się';const reason=hide?.active?`Ukrycie aktywne${hide.remaining>0?' · '+Math.ceil(hide.remaining)+' s':''}`:hide?.reason||'';b.title=reason;parent.querySelector('[data-hide-reason]').textContent=reason;}for(const b of parent.querySelectorAll('[data-origin-feat]')){const reason=originReason(p,b.dataset.originFeat);b.disabled=!!reason;b.title=reason;}for(const row of parent.querySelectorAll('[data-skill-source]')){const source=row.dataset.skillSource,key=String(p.id)+':'+source,reason=skillReason(p,source,skillPicks.get(key)),b=row.querySelector('[data-skill-confirm]');b.disabled=!!reason;b.title=reason;row.querySelector('[data-skill-reason]').textContent=reason;}
  for(const row of parent.querySelectorAll('[data-skill-challenge]')){const entry=h.state?.().skill_challenges?.nearby?.find(e=>e.id===row.dataset.skillChallenge),reason=challengeReason(p,entry),b=row.querySelector('[data-challenge-confirm]');b.disabled=!!reason;b.title=reason;row.querySelector('[data-challenge-reason]').textContent=reason;}}
 function reminderState(){let sessionKey,closed=new Set();const key=p=>String(p?.id)+':'+(p?.character_sheet?.training?.earned??((p?.character_sheet?.training?.spent||0)+(p?.character_sheet?.training?.points||0)));
  function sync(p,session){if(session!==sessionKey){sessionKey=session;closed.clear();}const points=p?.character_sheet?.training?.points,count=Number.isInteger(points)&&points>0?points:0;return {count,visible:count>0&&!closed.has(key(p))};}
  return {sync,dismiss(p,session){sync(p,session);if(p)closed.add(key(p));return sync(p,session);}};
 }
 function originReminderState(){let sessionKey,closed=new Set();function sync(p,session){if(session!==sessionKey){sessionKey=session;closed.clear();}const o=p?.character_sheet?.training?.origin;return {visible:!!p&&p.class_chosen!==false&&p.alive!==false&&o?.points===1&&!o.chosen&&!closed.has(String(p.id))};}return {sync,dismiss(p,session){sync(p,session);if(p)closed.add(String(p.id));}};}
 function createPrompt(h){const state=reminderState(),originState=originReminderState(),panel=node('aside','advancement-choice');panel.id='advancementChoice';panel.hidden=true;panel.setAttribute('aria-label','Dostępny rozwój postaci');const head=node('header'),title=node('strong','','Rozwiń postać'),description=node('p');description.setAttribute('aria-live','polite');const close=button('×',()=>{state.dismiss(h.player(),h.session?.());originState.dismiss(h.player(),h.session?.());refresh();});close.dataset.advancementDismiss='';close.setAttribute('aria-label','Przypomnij o rozwoju przy następnym logowaniu');head.append(title,close);const choices=node('div','advancement-choice-actions');
  const first=button('Wybierz pierwszy atut',()=>h.pick?h.pick('origin'):h.open('feats','origin'));first.dataset.advancementOrigin='';choices.append(first);
  for(const [tab,label]of [['abilities','Rozwiń cechy'],['feats','Wybierz atut']]){const open=button(label,()=>tab==='feats'&&h.pick?h.pick('general'):h.open(tab));open.dataset.advancementOpen=tab;choices.append(open);}panel.append(head,description,choices);document.getElementById('gameUI').append(panel);
  function refresh(){const p=h.player(),result=state.sync(p,h.session?.()),origin=originState.sync(p,h.session?.());panel.hidden=(!result.visible&&!origin.visible)||p?.class_chosen===false||p?.alive===false;title.textContent=origin.visible?'Wybierz pierwszy atut':'Rozwiń postać';first.hidden=!origin.visible;for(const b of choices.querySelectorAll('[data-advancement-open]'))b.hidden=!result.visible;description.textContent=(origin.visible?'Masz bezpłatny wybór atutu od poziomu 1. ':'')+(result.visible?`Dostępne wybory rozwoju: ${result.count}.`:'');}
  return {sync:refresh};
 }

 const api={abilities,advancement,abilityBuild,origin,skills,sync,choiceReason,buildCost,buildReason,asiReason,skillReason,challengeReason,trainingPacket,originReason,reminderState,originReminderState,createPrompt};root.BractwoSkillsUI=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
