/* UI21: original procedural spell art. No particles/timers survive a server event.
 * Ground fills/outlines always use server geometry; elevated art is decorative.
 * Fixed sample/branch budgets keep cost independent of spell radius/upcasting.
 */
(function(root){
  'use strict';
  const TAU=Math.PI*2,clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
  const FIELD_KEYS=new Set(['fog_cloud','sleet_storm','wall_of_stone','web','stinking_cloud','insect_plague','gust_of_wind','control_water','conjure_elemental','conjure_animals']);
  const PALETTES={fire:['#ff7739','#ffd276','#fff5d1'],cold:['#46b9ff','#a0eaff','#f7ffff'],lightning:['#7777ff','#c6c3ff','#ffffff'],radiant:['#eaba53','#fff2b7','#ffffff'],nature:['#53a365','#b2eaa2','#f2ffce'],acid:['#76bd36','#c4f878','#f4ffd7'],necrotic:['#843fad','#c17cf0','#f0ccff'],thunder:['#749bcc','#c5e9ff','#ffffff']};
  const hash=n=>{const v=Math.sin(n*127.1+31.7)*43758.5453;return v-Math.floor(v);};
  function palette(e){const key=e.spell_id||'',theme=(['ice_storm','cone_of_cold','moonbeam','ray_of_frost','sleet_storm'].includes(key)?'cold':['guiding_bolt','circle_star_arrow','starry_wisp','sunbeam','sunburst','guidance','foresight'].includes(key)?'radiant':['thunderwave','shatter'].includes(key)?'thunder':key==='ray_of_sickness'?'acid':e.visual?.theme);return PALETTES[theme]||e.visual?.colors||['#648bdb','#aaceff','#ffffff'];}
  function polygonContains(p,x,y){let sign=0;for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length],c=(b[0]-a[0])*(y-a[1])-(b[1]-a[1])*(x-a[0]);if(Math.abs(c)<1e-6)continue;const s=Math.sign(c);if(sign&&sign!==s)return false;sign=s;}return true;}
  function areaContains(area,x,y){return (area.circles||[]).some(([cx,cy,r])=>(cx-x)**2+(cy-y)**2<=r*r+1e-6)||(area.polygons||[]).some(p=>polygonContains(p,x,y));}
  function missilePoint(a,b,t,index,total=3){const dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy)||1,bend=(total<=3?[-96,32,105][index%3]:-150+300*index/Math.max(1,total-1))*Math.min(1,len/130),u=1-t;return [u*u*a[0]+2*u*t*((a[0]+b[0])/2-dy/len*bend)+t*t*b[0],u*u*a[1]+2*u*t*((a[1]+b[1])/2+dx/len*bend-18)+t*t*b[1]];}
  function path(ctx,area){ctx.beginPath();for(const [x,y,r]of area.circles||[]){ctx.moveTo(x+r,y);ctx.arc(x,y,r,0,TAU);}for(const p of area.polygons||[]){if(!p.length)continue;ctx.moveTo(...p[0]);for(let i=1;i<p.length;i++)ctx.lineTo(...p[i]);ctx.closePath();}}
  function line(ctx,points,color,width=1){if(points.length<2)return;ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(...points[0]);for(let i=1;i<points.length;i++)ctx.lineTo(...points[i]);ctx.stroke();}
  function ring(ctx,x,y,r,color,width=1,sy=1,start=0,end=TAU){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.ellipse(x,y,Math.max(.1,r),Math.max(.1,r*sy),0,start,end);ctx.stroke();}
  function orb(ctx,x,y,r,colors,alpha=1){ctx.save();ctx.globalAlpha*=alpha;const g=ctx.createRadialGradient(x,y,0,x,y,Math.max(1,r));g.addColorStop(0,colors[2]);g.addColorStop(.17,colors[1]);g.addColorStop(.4,colors[0]+'b0');g.addColorStop(1,colors[0]+'00');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,Math.max(.1,r),0,TAU);ctx.fill();ctx.restore();}
  function star(ctx,x,y,r,color,angle=0){ctx.fillStyle=color;ctx.beginPath();for(let i=0;i<8;i++){const a=angle+i*TAU/8,d=i%2?r*.27:r,px=x+Math.cos(a)*d,py=y+Math.sin(a)*d;if(i)ctx.lineTo(px,py);else ctx.moveTo(px,py);}ctx.closePath();ctx.fill();}
  function leaf(ctx,x,y,s,angle,color){const dx=Math.cos(angle)*s,dy=Math.sin(angle)*s;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x,y);ctx.quadraticCurveTo(x+dx*.5-dy*.48,y+dy*.5+dx*.48,x+dx,y+dy);ctx.quadraticCurveTo(x+dx*.5+dy*.48,y+dy*.5-dx*.48,x,y);ctx.fill();}
  function shard(ctx,x,y,s,color,angle=0){const dx=Math.cos(angle)*s,dy=Math.sin(angle)*s;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x+dx*.32,y+dy*.32);ctx.lineTo(x-dy*.35,y+dx*.35);ctx.lineTo(x-dx,y-dy);ctx.lineTo(x+dy*.35,y-dx*.35);ctx.closePath();ctx.fill();}
  function burst(ctx,x,y,colors,q,scale=1,ice=false){if(q<0||q>1)return;ctx.save();ctx.globalAlpha*=1-q;orb(ctx,x,y,28*scale,colors,.7);for(let i=0;i<12;i++){const a=i*2.3999,d=(8+28*q)*scale,xx=x+Math.cos(a)*d,yy=y+Math.sin(a)*d;if(ice)shard(ctx,xx,yy,5*scale,colors[i%3],a);else line(ctx,[[xx,yy],[xx+Math.cos(a)*7*scale,yy+Math.sin(a)*7*scale]],colors[i%2+1],2.4);}ctx.restore();}
  function lightningPoints(a,b,seed=0,amplitude=11,segments=18){const dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy)||1,pts=[];for(let i=0;i<=segments;i++){const t=i/segments,j=(i===0||i===segments)?0:(hash(i+seed*17)-.5)*amplitude*2;pts.push([a[0]+dx*t-dy/len*j,a[1]+dy*t+dx/len*j]);}return pts;}
  function lightning(ctx,a,b,colors,q,seed=0,branches=3){const fade=clamp((1-q)*1.9),frame=Math.floor(q*15),pts=lightningPoints(a,b,seed+frame,12,18);ctx.save();ctx.globalAlpha*=fade;
    line(ctx,pts,colors[0]+'32',17);line(ctx,pts,colors[0]+'b0',7);line(ctx,pts,colors[1],3.7);line(ctx,pts,colors[2],1.5);
    const dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy)||1;
    for(let i=0;i<Math.min(4,branches);i++){const n=5+i*3,start=pts[n],side=i%2?1:-1,end=[start[0]+dx*.11-dy/len*side*(20+i*7),start[1]+dy*.11+dx/len*side*(20+i*7)];line(ctx,lightningPoints(start,end,seed+13+i,5,5),colors[1]+'bc',1.5);}
    ctx.restore();
  }
  function beam(ctx,a,b,colors,q,icy=false,seed=0){ctx.save();ctx.globalAlpha*=Math.sin(Math.PI*Math.min(.98,q))*.95;const points=[];for(let i=0;i<=20;i++){const t=i/20,w=(i===0||i===20)?0:Math.sin(i*4.1+q*21+seed)*3;points.push([a[0]+(b[0]-a[0])*t+w,a[1]+(b[1]-a[1])*t-w]);}line(ctx,points,colors[0]+'40',19);line(ctx,points,colors[0]+'a0',10);line(ctx,points,colors[1],5);line(ctx,[a,b],colors[2],1.8);orb(ctx,...a,17,colors);burst(ctx,...b,colors,clamp(q*1.2),1.15,icy);if(icy)for(let i=0;i<7;i++){const t=(q*.8+i/7)%1,x=a[0]+(b[0]-a[0])*t,y=a[1]+(b[1]-a[1])*t;shard(ctx,x,y,7,colors[2]+'bb',-Math.PI/2);}ctx.restore();}
  function flame(ctx,x,y,w,h,colors,phase){const lean=Math.sin(phase)*w*.4;ctx.fillStyle=colors[0]+'8c';ctx.beginPath();ctx.moveTo(x-w*.5,y);ctx.bezierCurveTo(x-w,y-h*.4,x+lean-w*.15,y-h*.55,x+lean,y-h);ctx.bezierCurveTo(x+lean+w*.2,y-h*.55,x+w,y-h*.25,x+w*.5,y);ctx.closePath();ctx.fill();ctx.fillStyle=colors[1]+'d4';ctx.beginPath();ctx.moveTo(x-w*.23,y);ctx.quadraticCurveTo(x-w*.2,y-h*.38,x+lean*.4,y-h*.62);ctx.quadraticCurveTo(x+w*.5,y-h*.15,x+w*.23,y);ctx.closePath();ctx.fill();}
  function areaBounds(area){if(area.bounds)return area.bounds;const pts=[];for(const[x,y,r]of area.circles||[])pts.push([x-r,y-r],[x+r,y+r]);for(const p of area.polygons||[])pts.push(...p);return pts.length?[Math.min(...pts.map(p=>p[0])),Math.min(...pts.map(p=>p[1])),Math.max(...pts.map(p=>p[0])),Math.max(...pts.map(p=>p[1]))]:[0,0,0,0];}
  function samples(area,count=30){const b=areaBounds(area),out=[];for(let i=0;i<count;i++){const x=b[0]+hash(i+2)*(b[2]-b[0]),y=b[1]+hash(i+131)*(b[3]-b[1]);if(areaContains(area,x,y))out.push([x,y,i]);}return out;}
  function areaCenter(e){const a=e.area,b=areaBounds(a);return a.circles?.[0]?.slice(0,2)||[(b[0]+b[2])/2,(b[1]+b[3])/2];}
  function areaRadius(area){const b=areaBounds(area);return Math.max(1,(b[2]-b[0])/2,(b[3]-b[1])/2);}
  function exactGround(ctx,area,colors,q,persistent,top=false){ctx.save();path(ctx,area);if(!top){ctx.globalAlpha*=persistent?.09:clamp(1-q)*.13;ctx.fillStyle=colors[0];ctx.fill('nonzero');}else{ctx.globalAlpha*=persistent?.54:Math.sin(Math.PI*clamp(q,.04,.97))*.78;ctx.strokeStyle=colors[1];ctx.lineWidth=1.6;ctx.stroke();}ctx.restore();}
  function areaFlames(ctx,e,q,colors,now){const persistent=!!e.persistent;ctx.save();path(ctx,e.area);ctx.clip();for(const[x,y,i]of samples(e.area,36)){const p=persistent?(now*.6+hash(i+90))%1:clamp(q*1.2-hash(i+13)*.15),power=persistent?.6:Math.sin(Math.PI*p);ctx.globalAlpha=persistent?.43:(1-q)*.85;flame(ctx,x,y,16+hash(i)*15,(22+hash(i+10)*52)*power,colors,now*6+i);if(i%3===0){ctx.fillStyle=colors[1];ctx.fillRect(x+Math.sin(now+i)*6,y-p*50,2,3);}}ctx.restore();}
  function fireExplosion(ctx,e,q,colors){const[x,y]=areaCenter(e),r=areaRadius(e.area),t=clamp(q*1.8);ctx.save();path(ctx,e.area);ctx.clip();orb(ctx,x,y,r*(.35+.6*t),colors,(1-q)*.95);ring(ctx,x,y,r*t,colors[1]+'b0',Math.max(2,12*(1-q)));
    // Uneven radial plumes bloom out of a hot core, then separate into embers.
    for(let i=0;i<12;i++){const a=i*TAU/12+hash(i)*.22,d=r*(.13+.53*t),xx=x+Math.cos(a)*d,yy=y+Math.sin(a)*d;ctx.save();ctx.globalAlpha=(1-q)*.85;ctx.translate(xx,yy);ctx.rotate(a+Math.PI/2);flame(ctx,0,0,r*(.11+.14*(1-q)),r*(.14+.36*(1-q))*(.75+hash(i)*.4),colors,i+q*7);ctx.restore();ctx.globalAlpha=(1-q)*.9;const ember=r*clamp(q*1.9)*(.76+hash(i)*.2);line(ctx,[[x+Math.cos(a)*ember,y+Math.sin(a)*ember],[x+Math.cos(a)*(ember+9),y+Math.sin(a)*(ember+9)]],colors[1],2.2);}
    orb(ctx,x,y,r*(.16+.2*t),colors,(1-q)*.62);ctx.restore();}
  function fallingShards(ctx,e,q,colors,arrows=false){ctx.save();path(ctx,e.area);ctx.clip();for(const target of (e.targets||[]).slice(0,8)){if(!areaContains(e.area,target.x,target.y))continue;ctx.save();ctx.globalAlpha=(1-q)*.6;ring(ctx,target.x,target.y,9+q*12,colors[1],1.8,.45);if(!arrows)for(let j=0;j<3;j++)shard(ctx,target.x+(j-1)*6,target.y-5,6,colors[j],j*2);ctx.restore();}for(const[x,y,i]of samples(e.area,32)){const start=hash(i+40)*.34,t=clamp((q-start)/.47);if(q<start)continue;ctx.globalAlpha=clamp((1-q)*1.8);if(t<1){const xx=x-34*(1-t),yy=y-115*(1-t);line(ctx,[[xx-8,yy-25],[xx,yy]],colors[0]+'70',arrows?2:5);if(arrows){line(ctx,[[xx-8,yy-22],[xx,yy]],colors[1],1.6);line(ctx,[[xx-5,yy-2],[xx,yy],[xx+2,yy-6]],colors[2],1.8);}else shard(ctx,xx,yy,9+hash(i)*7,colors[1],Math.PI/2-.25);}else{const f=clamp((q-start-.47)/.3);if(arrows)line(ctx,[[x-6,y-18],[x,y]],colors[1]+'a0',1.6);else{ring(ctx,x,y,4+f*12,colors[1]+'80',1,.42);for(let j=0;j<3;j++)shard(ctx,x+Math.cos(j*2.1)*f*14,y+Math.sin(j*2.1)*f*11,5*(1-f)+.3,colors[j],j*2.1);}}}ctx.restore();}
  function natureField(ctx,e,q,colors,now){ctx.save();path(ctx,e.area);ctx.clip();const k=e.spell_id,grow=e.persistent?1:clamp(q*3.5);for(const[x,y,i]of samples(e.area,34)){ctx.globalAlpha=e.persistent?.72:Math.sin(Math.PI*clamp(q,.01,.99));const h=(k==='spike_growth'?13:23+hash(i)*15)*grow,sway=Math.sin(now*1.4+i)*3;line(ctx,[[x-5,y+3],[x+3,y-h*.38],[x+sway,y-h]],'#244a32',4);line(ctx,[[x-5,y+3],[x+3,y-h*.38],[x+sway,y-h]],colors[1],1.7);if(k==='spike_growth'){shard(ctx,x+3,y-h*.6,8,colors[2],-1.2);shard(ctx,x-4,y-5,6,colors[1],-2.5);}else{leaf(ctx,x+2,y-h*.35,10,-.55,colors[1]);leaf(ctx,x+sway,y-h*.7,12,-2.3,colors[0]);if(k==='plant_growth'&&i%4===0)star(ctx,x+sway,y-h,3.2,colors[2]);}}ctx.restore();}
  function pressure(ctx,e,q,colors){const[x,y]=areaCenter(e),r=areaRadius(e.area);ctx.save();path(ctx,e.area);ctx.clip();ctx.globalAlpha=clamp((1-q)*1.5);for(let i=0;i<3;i++){const t=clamp(q*1.7-i*.15);if(t>0)ring(ctx,x,y,r*t,colors[i],Math.max(1,6-i*1.5));}for(let i=0;i<18;i++){const a=i*2.3999,d=r*clamp(q*1.7)*(.6+hash(i)*.4);line(ctx,[[x+Math.cos(a)*d*.76,y+Math.sin(a)*d*.76],[x+Math.cos(a)*d,y+Math.sin(a)*d]],colors[1]+'b0',1.8);if(e.spell_id==='shatter')shard(ctx,x+Math.cos(a)*d,y+Math.sin(a)*d-12*Math.sin(q*Math.PI),4+hash(i)*4,colors[i%3],a);}ctx.restore();}
  function callLightning(ctx,e,q,colors,now){const[x,y]=areaCenter(e),r=e.area.circles?.[0]?.[2]||32;if(e.persistent&&e.phase!=='tick'){ctx.save();ctx.globalAlpha=.23;for(let i=0;i<4;i++){const cx=x+(i-1.5)*16,cy=y-155+Math.sin(now+i)*3;ctx.fillStyle=i%2?'#4a527d':'#65729b';ctx.beginPath();ctx.ellipse(cx,cy,21,11,0,0,TAU);ctx.fill();}ctx.restore();return;}
    // One strike per received cast/tick. No modulo loop can invent another hit.
    const reach=clamp(q/.14),from=[x-18,y-190],to=[x-18+(18*reach),y-190+190*reach];lightning(ctx,from,to,colors,q,Math.floor((e.x||0)+(e.target_y||0)),3);
    if(q>=.1){const t=clamp((q-.1)/.9);ctx.save();path(ctx,e.area);ctx.clip();orb(ctx,x,y,r*(.6+.6*t),colors,clamp(1-t)*.85);ring(ctx,x,y,r*clamp(t*3),colors[2],2);for(let i=0;i<8;i++){const a=i*TAU/8+.12,d=r*clamp(t*4),mid=[x+Math.cos(a+.16)*d*.55,y+Math.sin(a+.16)*d*.55],end=[x+Math.cos(a)*d,y+Math.sin(a)*d];line(ctx,[[x,y],mid,end],colors[1]+'b0',1.8);}ctx.restore();}
  }
  function moonColumn(ctx,e,q,colors,now){const[x,y]=areaCenter(e),r=e.area.circles?.[0]?.[2]||32,power=e.persistent?.38:e.phase==='tick'?(1-q)*.85:(1-q)*.7;ctx.save();const g=ctx.createLinearGradient(x,y-190,x,y);g.addColorStop(0,colors[0]+'00');g.addColorStop(.55,colors[1]+'15');g.addColorStop(1,colors[2]+'90');ctx.globalAlpha=power;ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(x-r*.65,y-190);ctx.lineTo(x+r*.65,y-190);ctx.lineTo(x+r,y);ctx.lineTo(x-r,y);ctx.closePath();ctx.fill();for(let i=0;i<5;i++){const p=(now*.3+i*.2)%1;line(ctx,[[x+(i-2)*r*.27,y-155*p],[x+(i-2)*r*.27,y-155*p-19]],colors[2]+'70',1.4);}ctx.restore();ctx.save();path(ctx,e.area);ctx.clip();orb(ctx,x,y,r,colors,power);ring(ctx,x,y,r*.74,colors[1]+'80',1.3);ctx.restore();}
  function acidArea(ctx,e,q,colors){ctx.save();path(ctx,e.area);ctx.clip();const[x,y]=areaCenter(e),r=areaRadius(e.area);orb(ctx,x,y,r*.8,colors,(1-q)*.45);for(let i=0;i<17;i++){const a=i*2.3999,d=r*.85*Math.sqrt(q)*hash(i+2),xx=x+Math.cos(a)*d,yy=y+Math.sin(a)*d-Math.sin(q*Math.PI)*16;ctx.globalAlpha=(1-q)*.9;ctx.fillStyle=colors[i%2];ctx.beginPath();ctx.ellipse(xx,yy,2+hash(i)*4,3+hash(i)*5,0,0,TAU);ctx.fill();if(q>.45)ring(ctx,xx,yy+4,4+q*4,colors[1],1,.45);}ctx.restore();}
  function sunburst(ctx,e,q,colors){const[x,y]=areaCenter(e),r=areaRadius(e.area);ctx.save();path(ctx,e.area);ctx.clip();orb(ctx,x,y,r*clamp(q*4,.2,1),colors,(1-q)*.73);ctx.globalAlpha=(1-q)*.7;for(let i=0;i<22;i++){const a=i*TAU/22,rr=r*(i%2?.7:1)*clamp(q*3);line(ctx,[[x+Math.cos(a)*rr*.2,y+Math.sin(a)*rr*.2],[x+Math.cos(a)*rr,y+Math.sin(a)*rr]],colors[i%2+1],i%2?2:5);}ring(ctx,x,y,r*clamp(q*2),colors[2],3);ctx.restore();}
  function cone(ctx,e,q,colors,cold){const area=e.area,[ox,oy]=area.origin||[e.x,e.y],[ux,uy]=area.direction||[1,0],len=area.length||areaRadius(area);ctx.save();path(ctx,area);ctx.clip();ctx.globalAlpha=clamp((1-q)*1.5);for(let i=0;i<15;i++){const spread=(i/14-.5)*len,t=clamp(q*2.3-hash(i)*.1),ex=ox+ux*len-uy*spread,ey=oy+uy*len+ux*spread,xx=ox+(ex-ox)*t,yy=oy+(ey-oy)*t;if(cold){line(ctx,[[ox,oy],[xx,yy]],colors[i%2]+'70',4+hash(i)*7);shard(ctx,xx,yy,8,colors[2],Math.atan2(uy,ux));}else{line(ctx,[[ox,oy],[xx,yy]],colors[0]+'55',9);flame(ctx,xx,yy,14,20+hash(i)*30,colors,q*12+i);}}ctx.restore();}
  function groundGlyphs(ctx,e,q,colors,now){ctx.save();path(ctx,e.area);ctx.clip();for(const[x,y,i]of samples(e.area,22)){const phase=e.persistent?(now*.22+hash(i))%1:clamp(q+hash(i)*.2);ctx.globalAlpha=e.persistent?.4:(1-q)*.72;if(e.spell_id==='sleep'){ring(ctx,x,y-phase*18,5,colors[1],1.4,1,-1.1,1.5);star(ctx,x+7,y-8-phase*18,2,colors[2]);}else{star(ctx,x,y-phase*20,2+hash(i)*2,colors[i%3],q+i);}}ctx.restore();}
  function meteor(ctx,e,q,colors){for(const[x,y,r]of (e.area.circles||[]).slice(0,4)){const t=clamp(q/.34);if(t<1){line(ctx,[[x-125*(1-t),y-210*(1-t)],[x-85*(1-t),y-140*(1-t)]],colors[0]+'a0',16);line(ctx,[[x-105*(1-t),y-175*(1-t)],[x-85*(1-t),y-140*(1-t)]],colors[1],7);orb(ctx,x-85*(1-t),y-140*(1-t),21,colors);}else{ctx.save();path(ctx,e.area);ctx.clip();const f=clamp((q-.34)/.66);orb(ctx,x,y,r*(.25+.5*f),colors,(1-f)*.8);ring(ctx,x,y,r*clamp(f*2),colors[1]+'a0',7*(1-f)+1);for(let i=0;i<8;i++){const a=i*2.3999,d=r*clamp(f*1.6)*.8;shard(ctx,x+Math.cos(a)*d,y+Math.sin(a)*d,7*(1-f)+1,colors[i%3],a);}ctx.restore();}}}
  function fieldImpacts(ctx,e,q,colors){ctx.save();path(ctx,e.area);ctx.clip();for(const target of (e.impacts?.length?e.impacts:e.targets||[]).slice(0,10)){const x=target.x,y=target.y,theme=target.damage_type,cc=PALETTES[theme]||colors;ctx.globalAlpha=clamp((1-q)*1.8);
    if(e.spell_id==='insect_plague'){for(let i=0;i<7;i++){const a=i*2.4+q*8,r=8+q*15,xx=x+Math.cos(a)*r,yy=y+Math.sin(a)*r*.7;line(ctx,[[xx-2,yy-2],[xx,yy],[xx+3,yy-2]],'#e4d292',1.2);}}
    else if(e.spell_id==='conjure_animals'){for(let i=0;i<3;i++)line(ctx,[[x-13+i*7,y-12+q*8],[x-6+i*7,y+8+q*8]],'#d2fff0',1.9);}
    else if(e.spell_id==='conjure_elemental'&&theme==='lightning')lightning(ctx,[x-15,y-24],[x+5,y+4],cc,q,2,1);
    else if(e.spell_id==='conjure_elemental'&&theme==='fire')flame(ctx,x,y+5,25,35*(1-q)+8,cc,q*8);
    else if(e.spell_id==='conjure_elemental')burst(ctx,x,y,cc,q,.75,theme==='cold');
    else{for(let i=0;i<3;i++)ring(ctx,x,y,8+q*18+i*4,PALETTES.cold[i],1.5,.45,q*3+i,q*3+i+3.9);}
  }ctx.restore();}
  function drawArea(ctx,e,q,colors,now){const area=e.area,key=e.spell_id;exactGround(ctx,area,colors,q,!!e.persistent);
    if(e.phase==='tick'&&FIELD_KEYS.has(key))fieldImpacts(ctx,e,q,colors);
    else if(key==='call_lightning')callLightning(ctx,e,q,colors,now);
    else if(key==='moonbeam')moonColumn(ctx,e,q,colors,now);
    else if(key==='meteor_swarm')meteor(ctx,e,q,colors);
    else if(key==='fireball')fireExplosion(ctx,e,q,colors);
    else if(key==='fire_storm'||key==='incendiary_cloud'){areaFlames(ctx,e,q,colors,now);if(key==='incendiary_cloud'){ctx.save();path(ctx,area);ctx.clip();for(const[x,y,i]of samples(area,10)){ctx.fillStyle=i%2?'#70544a30':'#a86b4830';ctx.beginPath();ctx.ellipse(x,y-13,30+Math.sin(now+i)*5,20,0,0,TAU);ctx.fill();}ctx.restore();}}
    else if(key==='ice_storm'||key==='conjure_volley')fallingShards(ctx,e,q,colors,key==='conjure_volley');
    else if(['entangle','plant_growth','spike_growth','circle_natures_sanctuary','circle_move_sanctuary'].includes(key))natureField(ctx,e,q,colors,now);
    else if(key==='acid_splash')acidArea(ctx,e,q,colors);
    else if(key==='thunderwave'||key==='shatter')pressure(ctx,e,q,colors);
    else if(key==='sunburst')sunburst(ctx,e,q,colors);
    else if(area.shape==='line'){const[ox,oy]=area.origin||[e.x,e.y],[ux,uy]=area.direction||[1,0],len=area.length||areaRadius(area);ctx.save();path(ctx,area);ctx.clip();if(key==='lightning_bolt')lightning(ctx,[ox,oy],[ox+ux*len,oy+uy*len],colors,q,3,4);else beam(ctx,[ox,oy],[ox+ux*len,oy+uy*len],colors,q,key==='cone_of_cold');ctx.restore();}
    else if(area.shape==='cone')cone(ctx,e,q,colors,key==='cone_of_cold');
    else if(key==='circle_lands_aid'){natureField(ctx,e,q,colors,now);for(const t of (e.targets||[]).slice(0,8)){if(e.impacts?.some(i=>i.id===t.id&&i.damage>0))necrotic(ctx,[e.x,e.y],[t.x,t.y-20],q,PALETTES.necrotic);}}
    else if(key==='mass_cure_wounds'){groundGlyphs(ctx,e,q,colors,now);for(const t of (e.targets||[]).slice(0,10))healing(ctx,t.x,t.y,q,colors,key);}
    else groundGlyphs(ctx,e,q,colors,now);
    exactGround(ctx,area,colors,q,!!e.persistent,true);
  }
  // Live status overlays have no independent effect lifetime.
  function mark(ctx,x,y,now,scale=1,alpha=1){ctx.save();ctx.globalAlpha*=alpha;const cy=y-49*scale,r=10*scale;ring(ctx,x,cy,r,'#eec768',2);for(let i=0;i<4;i++){const a=i*TAU/4;line(ctx,[[x+Math.cos(a)*r*.65,cy+Math.sin(a)*r*.65],[x+Math.cos(a)*r*1.45,cy+Math.sin(a)*r*1.45]],'#fff0ab',2);}ctx.globalAlpha*=.35+.1*Math.sin(now*3);ring(ctx,x,y+1,20*scale,'#eec768',2,.4);ctx.restore();}
  function vines(ctx,x,y,now,scale=1,alpha=1){ctx.save();ctx.globalAlpha*=alpha;for(let side=-1;side<=1;side+=2){const points=[];for(let j=0;j<=14;j++){const t=j/14;points.push([x+side*(13+Math.sin(t*9+now*1.5)*5)*scale,y-t*37*scale]);}line(ctx,points,'#173f2b',6*scale);line(ctx,points,'#66b857',3*scale);for(let j=3;j<14;j+=4){const a=points[j];leaf(ctx,...a,12*scale,side===1?-.65:-2.5,'#c2ea89');}}ctx.restore();}
  function drawStatuses(ctx,statuses,x,y,now=0,scale=1){if(!Array.isArray(statuses))return;scale=Math.max(.7,Math.min(2.2,Number(scale)||1));let marked=false,ensnared=false;for(const s of statuses){if(s.id==='concentration'||s.id==='ensnaring_ready')continue;if(s.spell_id==='hunters_mark'&&!marked){mark(ctx,x,y,now,scale);marked=true;}if(s.spell_id==='ensnaring_strike'&&s.id==='restrained'&&!ensnared){vines(ctx,x,y,now,scale);ensnared=true;}}}
  function thornWhip(ctx,a,b,q,colors){const dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy)||1,reach=q<.35?clamp(q/.35):q>.75?clamp((1-q)/.25):1,pts=[];for(let i=0;i<=24;i++){const t=i/24*reach,w=Math.sin(t*Math.PI)*Math.sin(t*9-q*11)*17*(1-q*.6);pts.push([a[0]+dx*t-dy/len*w,a[1]+dy*t+dx/len*w]);}ctx.save();ctx.globalAlpha=clamp((1-q)*3);line(ctx,pts,'#254329',6);line(ctx,pts,colors[1],2.7);for(let i=3;i<24;i+=3){const p=pts[i],side=i%2?1:-1;line(ctx,[p,[p[0]-dy/len*side*7-dx/len*4,p[1]+dx/len*side*7-dy/len*4]],colors[2],1.6);}if(q>.32&&q<.8){ring(ctx,b[0],b[1],10+Math.sin(q*8)*2,colors[1],2.5,.7);burst(ctx,...b,colors,(q-.32)/.48,.7);}ctx.restore();}
  function necrotic(ctx,a,b,q,colors,beamStyle=false){ctx.save();ctx.globalAlpha=clamp((1-q)*1.7);if(beamStyle){const pts=lightningPoints(a,b,Math.floor(q*11),6,14);line(ctx,pts,colors[0]+'60',13);line(ctx,pts,colors[1],3.1);}for(let i=0;i<10;i++){const a0=i*2.3999+q*2,r=(1-q)*37+5,x=b[0]+Math.cos(a0)*r,y=b[1]+Math.sin(a0)*r*.7;line(ctx,[[x,y],[b[0]+Math.cos(a0+.6)*r*.45,b[1]+Math.sin(a0+.6)*r*.35]],colors[i%2]+'c0',2.4);leaf(ctx,x,y,8,-a0,colors[0]);}orb(ctx,...b,24,colors,(1-q)*.45);ctx.restore();}
  function projectile(ctx,e,a,b,q,colors){const key=e.spell_id,t=clamp(q/.64),dx=b[0]-a[0],dy=b[1]-a[1],angle=Math.atan2(dy,dx),pos=[a[0]+dx*t,a[1]+dy*t],tail=[a[0]+dx*Math.max(0,t-.17),a[1]+dy*Math.max(0,t-.17)];if(t<1){line(ctx,[tail,pos],colors[0]+'35',16);line(ctx,[tail,pos],colors[1]+'ba',4);orb(ctx,...pos,key==='guiding_bolt'?22:16,colors,.85);if(key==='guiding_bolt'||key==='circle_star_arrow'||key==='starry_wisp'){star(ctx,...pos,key==='guiding_bolt'?12:8,colors[2],angle+q*3);for(let i=0;i<4;i++){const f=Math.max(0,t-.035*(i+1));star(ctx,a[0]+dx*f+Math.sin(i*3+q*11)*5,a[1]+dy*f+Math.cos(i*3+q*11)*5,3-i*.5,colors[1]);}}else if(key==='fire_bolt'||key==='produce_flame'){for(let i=0;i<3;i++)leaf(ctx,pos[0]-Math.cos(angle)*i*7,pos[1]-Math.sin(angle)*i*7,12+i*3,angle+Math.PI+Math.sin(q*13+i)*.25,colors[i%2]);}else if(key==='ray_of_sickness'){for(let i=0;i<4;i++)ring(ctx,pos[0]-Math.cos(angle)*i*8,pos[1]-Math.sin(angle)*i*8,3,colors[1],1.3);}else star(ctx,...pos,7,colors[2],q*4);}else{burst(ctx,...b,colors,(q-.64)/.36,key==='guiding_bolt'?1.35:1);if(key==='guiding_bolt'){ctx.save();ctx.globalAlpha=clamp((1-q)*3);star(ctx,b[0],b[1]-24,14,colors[2],q);ring(ctx,b[0],b[1]-24,20,colors[1],1.4);ctx.restore();}}}
  function healing(ctx,x,y,q,colors,key){const big=key==='heal'||key==='mass_cure_wounds';ctx.save();ctx.globalAlpha=Math.sin(Math.PI*clamp(q,.01,.99));orb(ctx,x,y-24,big?52:38,colors,.22);ring(ctx,x,y+1,24+q*9,colors[1]+'90',1.8,.38);for(let side=0;side<2;side++){const pts=[];for(let i=0;i<16;i++){const t=i/15,angle=t*TAU*1.5+q*4+side*Math.PI;pts.push([x+Math.cos(angle)*(19-t*8),y-t*58-q*5]);}line(ctx,pts,colors[side]+'85',1.6);}for(let i=0;i<(big?10:7);i++){const t=(q*.75+i/10)%1,angle=i*2.4+q,x0=x+Math.cos(angle)*(15+hash(i)*11),y0=y-t*61;if(key==='healing_word'||key==='heal')star(ctx,x0,y0,3+hash(i)*2,colors[2],.3);else leaf(ctx,x0,y0,7,-1.3+Math.sin(i),colors[i%3]);}if(key==='heal'){line(ctx,[[x-8,y-32],[x+8,y-32]],colors[2],3);line(ctx,[[x,y-40],[x,y-24]],colors[2],3);}ctx.restore();}
  function teleport(ctx,a,b,q,colors,nature=false){ctx.save();for(let side=0;side<2;side++){const pos=side?b:a,p=side?clamp((q-.12)/.88):q,scale=side?Math.sin(p*Math.PI/2):1-p;ctx.globalAlpha=side?Math.sin(Math.PI*p):1-p;orb(ctx,pos[0],pos[1]-4,40*scale+1,colors,.42);for(let i=0;i<3;i++)ring(ctx,pos[0],pos[1]+16-i*20,Math.max(1,scale*(22-i*3)),colors[i],2.3,.38);for(let i=0;i<12;i++){const angle=i*2.4+q*(side?5:-5),r=(12+hash(i)*20)*scale,xx=pos[0]+Math.cos(angle)*r,yy=pos[1]+12-i*4;const to=[xx+Math.cos(angle+.7)*10*scale,yy-8];if(nature)leaf(ctx,xx,yy,8,angle,colors[1]);else line(ctx,[[xx,yy],to],colors[i%3],2);}}ctx.restore();}
  function shield(ctx,x,y,q,colors,armor=false){const scale=clamp(q*5,.25,1);ctx.save();ctx.globalAlpha=clamp((1-q)*2);const pts=[[-23,-48],[0,-61],[23,-48],[19,-15],[0,0],[-19,-15],[-23,-48]].map(([dx,dy])=>[x+dx*scale,y+dy*scale]);ctx.fillStyle=colors[0]+'18';ctx.beginPath();ctx.moveTo(...pts[0]);for(const p of pts.slice(1))ctx.lineTo(...p);ctx.closePath();ctx.fill();line(ctx,pts,colors[0]+'55',8);line(ctx,pts,colors[2],2);line(ctx,[[x,y-57*scale],[x,y-6*scale]],colors[1]+'a0',1.3);if(armor){for(let i=0;i<4;i++){const yy=y-45+i*10;line(ctx,[[x-16,yy],[x,yy+6],[x+16,yy]],colors[1],1.5);}ring(ctx,x,y-27,33,colors[1]+'80',1.5,.8,q*3,q*3+Math.PI*1.3);}else star(ctx,x,y-31,10,colors[2],Math.PI/4);ctx.restore();}
  function skin(ctx,x,y,q,colors,stone=false){ctx.save();ctx.globalAlpha=Math.sin(Math.PI*clamp(q,.01,.99));for(let i=0;i<9;i++){const a=i*2.3999+q*.55,r=24*(1-q*.35),xx=x+Math.cos(a)*r,yy=y-23+Math.sin(a)*r*.95;if(stone){const pts=[[xx-7,yy-5],[xx+4,yy-8],[xx+9,yy+2],[xx+2,yy+8],[xx-7,yy+3],[xx-7,yy-5]];ctx.fillStyle=i%2?'#899a92':'#b9c9bb';ctx.beginPath();ctx.moveTo(...pts[0]);for(const p of pts.slice(1))ctx.lineTo(...p);ctx.fill();line(ctx,pts,'#e0ead6',1.2);}else{line(ctx,[[xx-3,yy+9],[xx-5,yy-3],[xx,yy-12]],'#795e39',5);line(ctx,[[xx-3,yy+9],[xx-5,yy-3],[xx,yy-12]],'#c1bc78',1.8);leaf(ctx,xx,yy-4,9,a,colors[1]);}}ctx.restore();}
  function bindings(ctx,x,y,q,colors){ctx.save();ctx.globalAlpha=clamp((1-q)*2);for(let i=0;i<3;i++){const yy=y-9-i*17;ring(ctx,x,yy,19+Math.sin(q*9+i)*2,colors[0]+'80',5,.4);ring(ctx,x,yy,19+Math.sin(q*9+i)*2,colors[2],1.6,.4);for(const side of[-1,1])star(ctx,x+side*19,yy,3.5,colors[1],Math.PI/4);}for(const side of[-1,1])line(ctx,[[x+side*19,y-50],[x+side*23,y-22],[x+side*19,y+3]],colors[1]+'99',2);ctx.restore();}
  function aura(ctx,e,x,y,q,colors,now){const key=e.spell_id,fade=Math.sin(Math.PI*clamp(q,.01,.99));
    if(key==='shield'||key==='mage_armor'){shield(ctx,x,y,q,colors,key==='mage_armor');return;}
    if(key==='barkskin'||key==='stoneskin'){skin(ctx,x,y,q,colors,key==='stoneskin');return;}
    if(key==='hold_person'||key==='hold_monster'){bindings(ctx,x,y,q,colors);return;}
    ctx.save();ctx.globalAlpha=fade;
    if(key==='longstrider'||key==='freedom_of_movement'){for(const side of[-1,1])for(let i=0;i<3;i++){const xx=x+side*(10+q*12),yy=y-i*8;line(ctx,[[xx-side*13,yy+5],[xx,yy],[xx+side*8,yy-2]],colors[i],2);if(key==='freedom_of_movement')shard(ctx,xx+side*q*18,yy-q*11,4,colors[2],q*3);}ring(ctx,x,y+2,25,colors[1]+'a0',1.4,.32);}
    else if(['circle_wrath_of_sea','circle_oceanic_gift','circle_oceanic_gift_shared'].includes(key)){for(let i=0;i<3;i++){const a=q*3+i*TAU/3;ring(ctx,x,y-9-i*10,26,PALETTES.cold[i],2.4,.4,a,a+3.9);for(let j=0;j<3;j++){const angle=a+j*.25;star(ctx,x+Math.cos(angle)*26,y-9-i*10+Math.sin(angle)*10,2.5,PALETTES.cold[2]);}}if(key!=='circle_wrath_of_sea'){for(const side of[-1,1])line(ctx,[[x+side*12,y-35],[x+side*29,y-48],[x+side*21,y-30]],PALETTES.cold[1],2);}}
    else if(key.startsWith('circle_star_')){const nodes=[[-17,-20],[-9,-48],[7,-62],[22,-39],[7,-22],[-5,-7]];line(ctx,nodes.map(([dx,dy])=>[x+dx,y+dy]),'#a7d3ffa0',1.4);for(let i=0;i<nodes.length;i++)star(ctx,x+nodes[i][0],y+nodes[i][1],3+Math.sin(q*4+i),PALETTES.radiant[2]);if(key==='circle_star_archer'){ring(ctx,x+4,y-35,19,PALETTES.radiant[1],2,1,-1.1,1.1);line(ctx,[[x+12,y-52],[x+12,y-18],[x+12,y-35],[x+32,y-35]],PALETTES.radiant[2],1.4);}else if(key==='circle_star_chalice'){line(ctx,[[x-13,y-42],[x-9,y-25],[x,y-19],[x+9,y-25],[x+13,y-42]],PALETTES.radiant[1],2);line(ctx,[[x,y-19],[x,y-9],[x-8,y-9],[x+8,y-9]],PALETTES.radiant[2],2);}else line(ctx,[[x-9,y-52],[x+12,y-43],[x+3,y-34],[x+13,y-22],[x-6,y-13]],PALETTES.radiant[1],2.5);}
    else if(key==='arcane_recovery'){for(let i=0;i<10;i++){const angle=i*2.4+q*3,r=32*(1-q)+7,xx=x+Math.cos(angle)*r,yy=y-22+Math.sin(angle)*r-q*19;shard(ctx,xx,yy,6,colors[i%3],Math.PI/2);}orb(ctx,x,y-25,37,colors,.4);ring(ctx,x,y+1,24,colors[1],2,.38);}
    else if(key==='alarm'){for(const side of[-1,1])for(const top of[-1,1]){const xx=x+side*26,yy=y-22+top*20;star(ctx,xx,yy,6,colors[2],Math.PI/4);line(ctx,[[xx-side*7,yy],[xx,yy],[xx,yy-top*7]],colors[1],1.5);}ring(ctx,x,y-22,15+q*10,colors[1],1.8);}
    else if(key==='speak_with_animals'){for(let i=0;i<3;i++)ring(ctx,x+14,y-44,8+i*7,colors[i],1.6,.8,-.7,.7);leaf(ctx,x-7,y-41,14,-1.8,colors[1]);leaf(ctx,x-9,y-28,13,-2.6,colors[0]);}
    else if(key==='escape_grapple'){for(let i=0;i<8;i++){const angle=i*TAU/8,r=15+q*27,xx=x+Math.cos(angle)*r,yy=y-20+Math.sin(angle)*r*.7;line(ctx,[[xx-3,yy-5],[xx+3,yy+5]],colors[1],2.5);}}
    else if(key==='guidance'||key==='foresight'){const yy=y-60-q*7;orb(ctx,x,yy,30,colors,.35);if(key==='guidance'){star(ctx,x,yy,13,colors[2],q*.4);ring(ctx,x,yy,20,colors[1],1.5,1,q*2,q*2+4.9);for(let i=0;i<3;i++)star(ctx,x+Math.cos(i*2.1+q)*26,yy+Math.sin(i*2.1+q)*19,3,colors[1]);}else{line(ctx,[[x-23,yy],[x-11,yy-10],[x+10,yy-10],[x+23,yy],[x+10,yy+10],[x-11,yy+10],[x-23,yy]],colors[1],2);ring(ctx,x,yy,6,colors[2],2);star(ctx,x,yy,3,colors[2]);}}
    else if(key==='water_breathing'){for(let i=0;i<9;i++){const p=(q+i*.1)%1,xx=x+Math.sin(i*2.4+q)*22,yy=y-p*65;ring(ctx,xx,yy,3+hash(i)*4,colors[1],1.5);line(ctx,[[xx-2,yy-2],[xx,yy-3]],colors[2],1);}ring(ctx,x,y-30,27,colors[0]+'88',1.4,.8);}
    else if(key==='blur'){for(const side of[-1,1]){const dx=side*(7+q*12);ctx.globalAlpha=fade*.42;ring(ctx,x+dx,y-44,9,colors[1],1.7);line(ctx,[[x+dx-13,y-4],[x+dx-10,y-27],[x+dx,y-33],[x+dx+10,y-27],[x+dx+13,y-4]],colors[1],2);}}
    else if(key==='protection_from_energy'){for(let i=0;i<3;i++){const a=q*2.5+i*TAU/3,xx=x+Math.cos(a)*29,yy=y-26+Math.sin(a)*31;ring(ctx,x,y-26,31,colors[i]+'80',1.5,.95,a,a+1.4);star(ctx,xx,yy,5,colors[2],a);}shield(ctx,x,y,q,PALETTES.fire,false);}
    else if(key==='shillelagh'){const a=[x+15,y-3],b=[x+20,y-53];line(ctx,[a,b],'#775b37',6);line(ctx,[a,b],colors[1]+'b0',2);for(let i=0;i<7;i++){const t=i/7,xx=x+17+Math.sin(t*12+q*6)*9,yy=y-4-t*48;leaf(ctx,xx,yy,9,i%2?-2.3:-.6,colors[i%3]);}orb(ctx,...b,16,colors,.5);}
    else if(key==='fount_of_moonlight'){ring(ctx,x,y-49,14,colors[2],3,1,-1.8,1.5);for(let i=0;i<8;i++)star(ctx,x+Math.cos(i*2.4+q)*28,y-16-Math.sin(i*2.4+q)*25-q*16,2.7,colors[i%3]);orb(ctx,x,y-23,42,colors,.22);}
    else if(key==='tree_stride'){for(const side of[-1,1]){line(ctx,[[x+side*19,y],[x+side*23,y-31],[x+side*15,y-57]],colors[0],4);for(let i=0;i<3;i++)leaf(ctx,x+side*21,y-20-i*11,12,side>0?-.5:-2.6,colors[1]);}}
    else{ring(ctx,x,y+1,25+q*5,colors[1],1.8,.35);for(let i=0;i<12;i++){const a=i*2.3999+q*3,r=24*(1-q*.25),xx=x+Math.cos(a)*r,yy=y-12-i*3;line(ctx,[[xx,yy],[xx+Math.cos(a+.6)*8,yy-7]],colors[i%3],1.8);if(i%3===0)star(ctx,xx,yy,4,colors[2],a);}orb(ctx,x,y-26,33,colors,.18);}
    ctx.restore();
  }
  function summon(ctx,e,x,y,q,colors){ctx.save();ctx.globalAlpha=Math.sin(Math.PI*clamp(q,.01,.99));for(let i=0;i<2;i++){const points=[];for(let j=0;j<26;j++){const t=j/25,a=t*TAU*1.5+q*4+i*Math.PI;points.push([x+Math.cos(a)*(27-t*12),y-t*66]);}line(ctx,points,colors[i]+'b0',2.4);}for(let i=0;i<10;i++){const a=i*2.4+q*4;leaf(ctx,x+Math.cos(a)*27,y-10-Math.sin(a)*20-q*30,8,a,colors[i%3]);}ring(ctx,x,y+1,29,colors[1],2,.35);star(ctx,x,y-35,13*(1-q)+3,colors[2],q*2);ctx.restore();}
  function familyFor(e){const key=e.spell_id||'',style=e.visual?.style||'projectile';if(FIELD_KEYS.has(key))return 'field';if(e.area&&style!=='chain')return 'area';if(key==='thorn_whip')return 'vine-whip';if(['shocking_grasp','chain_lightning'].includes(key))return 'lightning';if(['blight','finger_of_death'].includes(key))return 'necrotic';if(['ray_of_sickness','guiding_bolt','circle_star_arrow','starry_wisp','fire_bolt','produce_flame'].includes(key))return 'projectile';if(['hold_person','hold_monster'].includes(key))return 'bindings';if(key==='polymorph'||key.startsWith('wild_shape')||['shape','companion','summon','familiar','wild_familiar'].includes(style))return 'summon';if(key==='circle_moonlight_step'||(key==='tree_stride'&&e.phase==='recast'))return 'teleport';if(['attack','save'].includes(style))return 'projectile';return style;}
  function draw(ctx,e,q,now=0){if(e.kind!=='spell')return false;q=clamp(Number(q)||0);now=Number(now)||0;const colors=palette(e),style=e.visual?.style||'projectile',key=e.spell_id||'',family=familyFor(e),a=[e.x,e.y-20],b=[e.target_x??e.x,(e.target_y??e.y)-20];
    // game.js suppresses a persistent duplicate only when its live field was drawn.
    ctx.save();
    if(e.area&&style!=='chain')drawArea(ctx,e,q,colors,now);
    else if(key==='circle_wrath_strike'&&(!e.targets?.[0]||e.targets[0].id===(e.source?.id??e.source_id))){aura(ctx,{...e,spell_id:'circle_wrath_of_sea'},a[0],a[1]+20,q,colors,now);}
    else if(key==='circle_wrath_strike'){const target=e.targets?.[0],dest=target?[target.x,target.y-14]:b,dx=dest[0]-a[0],dy=dest[1]-a[1],len=Math.hypot(dx,dy)||1;ctx.globalAlpha=clamp((1-q)*1.7);for(let j=0;j<3;j++){const t=clamp(q*2.3-j*.13),xx=a[0]+dx*t,yy=a[1]+dy*t;line(ctx,[[xx-dy/len*15,yy+dx/len*15],[xx+dx/len*7,yy+dy/len*7],[xx+dy/len*15,yy-dx/len*15]],PALETTES.cold[j],4-j);for(const side of[-1,1])star(ctx,xx+dy/len*side*16,yy-dx/len*side*16,3,PALETTES.cold[2]);}burst(ctx,...dest,PALETTES.cold,q,.8);}
    else if(key==='beast_trample'){ctx.globalAlpha=clamp((1-q)*1.8);ring(ctx,b[0],b[1]+20,13+q*27,'#dacaa3',3,.45);for(let i=0;i<11;i++){const angle=i*2.3999,d=7+q*30;shard(ctx,b[0]+Math.cos(angle)*d,b[1]+20+Math.sin(angle)*d*.45-Math.sin(q*Math.PI)*13,5*(1-q)+1,i%2?'#ac9b7e':'#e0ceb0',angle);}line(ctx,[[b[0]-5,b[1]+19],[b[0]+2,b[1]+16],[b[0]+10,b[1]+22]],'#9b8668',2);}
    else if(key==='thorn_whip')thornWhip(ctx,a,b,q,colors);
    else if(key==='shocking_grasp'){lightning(ctx,a,b,colors,q,2,2);for(let i=0;i<3;i++){const angle=i*TAU/3+q;lightning(ctx,[b[0]+Math.cos(angle)*20,b[1]+Math.sin(angle)*20],b,colors,q,i+7,0);}burst(ctx,...b,colors,q,.8);}
    else if(key==='blight'||key==='finger_of_death')necrotic(ctx,a,b,q,colors,key==='finger_of_death');
    else if(style==='missiles'){const progress=clamp(q/.75),count=Math.max(1,Math.min(11,e.shots||3));for(let i=0;i<count;i++){const pts=[];for(let k=0;k<12;k++){const t=Math.max(0,progress-(11-k)*.013);pts.push(missilePoint(a,b,t,i,count));}line(ctx,pts,colors[0]+'60',10);line(ctx,pts,colors[1],3.4);const pos=missilePoint(a,b,progress,i,count);if(progress<1){orb(ctx,...pos,15,colors);star(ctx,...pos,5,colors[2],q*4+i);}else if(i<3)burst(ctx,...b,colors,(q-.75)/.25,1.2);}}
    else if(style==='vines'){vines(ctx,b[0],b[1]+20,now,1,Math.sin(Math.PI*q));burst(ctx,b[0],b[1]+20,colors,q,.8);}
    else if(style==='mark')mark(ctx,b[0],b[1]+20,now,1,Math.sin(Math.PI*q));
    else if(style==='beam'){const count=Math.max(1,Math.min(11,e.shots||1));for(let i=0;i<count;i++)beam(ctx,[a[0],a[1]+(i-(count-1)/2)*7],b,colors,q,key==='ray_of_frost',i);}
    else if(style==='chain'){const targets=(e.targets||[]).slice(0,12),main=targets[0];if(main){const end=[main.x,main.y-20];lightning(ctx,a,end,colors,q,2,3);burst(ctx,...end,colors,q,.7);for(let i=1;i<targets.length;i++){const target=targets[i],dst=[target.x,target.y-20];lightning(ctx,end,dst,colors,q,11+i,1);burst(ctx,...dst,colors,q,.6);}}}
    else if(family==='projectile')projectile(ctx,e,a,b,q,colors);
    else if(family==='teleport')teleport(ctx,a,b,q,colors,key==='tree_stride');
    else if(style==='heal'){const targets=e.targets?.length?e.targets.slice(0,10):[{x:b[0],y:b[1]+20}];for(const t of targets)healing(ctx,t.x,t.y,q,colors,key);}
    else if(family==='summon')summon(ctx,e,b[0],b[1]+20,q,colors);
    else if(['hold_person','hold_monster','water_breathing'].includes(key)){const targets=e.targets?.length?e.targets.slice(0,10):[{x:b[0],y:b[1]+20}];for(const target of targets)aura(ctx,e,target.x,target.y,q,colors,now);}
    else aura(ctx,e,b[0],b[1]+20,q,colors,now);
    ctx.restore();return true;
  }
  const api={draw,drawStatuses,areaContains,missilePoint,familyFor};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.BractwoSpellVFX=api;
})(typeof globalThis!=='undefined'?globalThis:this);
