/* A wizard owns a book; browsing and preparation drafts never change cast access. */
(function(root){'use strict';
 const drafts=new Map();
 const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 const button=(text,action,disabled=false)=>{const e=node('button',text);e.type='button';e.disabled=disabled;e.addEventListener('click',action);return e;};
 const book=p=>p?.class_id==='mage'&&p.character_sheet?.caster?.spellbook?.enabled?p.character_sheet.caster.spellbook:null;
 const normalize=section=>['book','learn','prepare'].includes(section)?section:section==='memorize'?'prepare':'ready';
 const leveled=s=>Number(s?.circle)>0&&!s.feature;
 function state(p,s){const b=book(p);if(!b||!leveled(s))return null;const known=b.known?.includes(s.id)||false,prepared=b.prepared?.includes(s.id)||false;return {known,prepared,learnable:b.learning_choices?.includes(s.id)||false,ritual:known&&!!s.ritual&&(p.spell_profiles?.[s.id]?.ritual_available!==false)};}
 function draft(p){const b=book(p);if(!b)return null;const id=String(p.id),baseline=JSON.stringify(b.prepared||[]);let d=drafts.get(id);if(!d||d.baseline!==baseline){d={baseline,prepared:new Set(b.prepared||[]),forget:'',prepare:''};drafts.set(id,d);}const known=new Set(b.known||[]);for(const key of d.prepared)if(!known.has(key))d.prepared.delete(key);return d;}
 function changeReason(p,forRest=false){if(!p||p.alive===false||p.hp<=0)return 'Postać musi żyć.';if(p.form||p.polymorph)return 'Najpierw zakończ przemianę.';if(!forRest&&p.combat_remaining>0)return 'Zmiany są dostępne poza walką.';if(p.rest?.remaining>0)return 'Trwa odpoczynek. Zmiany zostaną zatwierdzone po jego ukończeniu.';if(p.character_sheet?.caster?.channel?.key)return 'Najpierw zakończ trwającą czynność.';if(p.rest_block_reason==='moving')return 'Zatrzymaj się, aby pracować z księgą.';return '';}
 function learnPacket(p,id){const b=book(p);return b&&!changeReason(p)&&b.learning_choices?.includes(id)?{type:'wizard_learn',spell:id}:null;}
 function freePacket(p){const b=book(p),d=draft(p);if(!b||!d||changeReason(p))return null;const known=new Set(b.known||[]),prepared=b.prepared||[],ids=[...d.prepared],added=ids.filter(id=>!prepared.includes(id));if(!added.length||ids.length>b.prepared_limit||added.length>Number(b.free_preparations||0)||prepared.some(id=>!d.prepared.has(id))||ids.some(id=>!known.has(id)))return null;return {type:'wizard_prepare',spells:ids};}
 function restPacket(p,world,kind){const b=book(p),d=draft(p);if(!b||!d||changeReason(p,true))return null;const rest=root.BractwoRestUI?.model(p,world?.rest_rules);if(!rest||(kind==='long'?!rest.canLong:!rest.canShort))return null;
  if(kind==='long'){const ids=[...d.prepared];if(ids.length>b.prepared_limit||ids.some(id=>!b.known?.includes(id)))return null;return {type:'rest',kind:'long',recover:true,wizard_preparation:{prepared:ids}};}
  if(kind!=='short'||!b.memorize_available||!b.prepared?.includes(d.forget)||!b.known?.includes(d.prepare)||b.prepared?.includes(d.prepare))return null;
  return {type:'rest',kind:'short',recover:true,wizard_preparation:{memorize:{forget:d.forget,prepare:d.prepare}}};
 }
 function grantSummary(b){const groups=new Map(),names={abjuration:'Odpychanie',divination:'Wróżbiarstwo',evocation:'Ewokacja',illusion:'Iluzja'};for(const g of b.learning_grants||[]){if(!(g.remaining>0))continue;const key=g.max_circle+':'+(g.school||''),entry=groups.get(key)||{circle:g.max_circle,school:g.school,count:0};entry.count+=g.remaining;groups.set(key,entry);}return [...groups.values()].map(g=>`${g.count} × do ${g.circle}. kręgu${g.school?' · '+(names[g.school]||g.school):''}`).join(' / ');}
 function pending(p){const b=book(p);if(!b)return null;if(b.pending_learning&&b.learning_choices?.length)return {id:'wizard_book',tab:'spells',section:'learn',title:'Twoja księga czarów',description:`Możesz poznać nowe czary. Dostępne wybory: ${b.learning_credits||b.learning_choices.length}.`,label:'Wybierz czary do księgi',token:'learn:'+b.learning_credits+':'+(b.known||[]).length};if(b.free_preparations>0&&(b.prepared||[]).length<b.prepared_limit&&(b.known||[]).some(id=>!b.prepared?.includes(id)))return {id:'wizard_book',tab:'spells',section:'prepare',title:'Przygotuj czary',description:`Masz wolne miejsca na przygotowane czary: ${Math.min(b.free_preparations,b.prepared_limit-(b.prepared||[]).length)}.`,label:'Otwórz przygotowanie',token:'prepare:'+b.free_preparations+':'+(b.prepared||[]).length};return null;}
 function sections(all,p,section){if(!book(p))return all;const mode=normalize(section);return all.map(group=>({...group,entries:group.entries.filter(({spec})=>{const s=state(p,spec);if(!s)return mode==='ready';if(mode==='learn')return !s.known;if(mode==='book'||mode==='prepare')return s.known;return s.prepared;})})).filter(group=>group.entries.length);}
 function header(parent,p,w,h,section){const b=book(p);if(!b)return;const mode=normalize(section),nav=node('nav',undefined,'sheet-subtabs wizard-book-tabs');nav.setAttribute('aria-label','Księga czarodzieja');nav.setAttribute('role','tablist');
  for(const [id,label]of [['ready','Gotowe'],['book','Księga'],['learn','Nauka'],['prepare','Przygotuj']]){const tab=button(label,()=>h.open('spells',id));tab.dataset.wizardTab=id;tab.classList.toggle('active',mode===id);tab.setAttribute('role','tab');tab.setAttribute('aria-selected',String(mode===id));nav.append(tab);}parent.append(nav);
  const summary=node('section',undefined,'wizard-book-summary');summary.append(node('strong',`Księga: ${(b.known||[]).length} czarów · przygotowane: ${(b.prepared||[]).length}/${b.prepared_limit}`),node('small','Sztuczki i zdolności klasy nie zajmują miejsc na przygotowane czary.'));
  if(b.legacy_migrated){const note=node('details',undefined,'wizard-book-migration');note.append(node('summary','Twoja dotychczasowa księga została zachowana'),node('p','Wcześniej dostępne czary są zapisane w księdze. Przygotowany zestaw uwzględnia dotychczasowe skróty; możesz go zmienić podczas długiego odpoczynku.'));summary.append(note);}
  if(mode==='learn'){summary.append(node('p',`Bezpłatne wybory do księgi: ${b.learning_credits||0}. Sześć czarów 1. kręgu na początek, potem dwa na każdy poziom.`));if(b.learning_grants?.length)summary.append(node('small',grantSummary(b),'wizard-learning-grants'));summary.append(node('small','Wybór „Zapisz w księdze” jest trwały. Poznanie czaru nie przygotowuje go do zwykłego rzucania. Zaległe wybory zachowują krąg dostępny przy ich zdobyciu.'));if(b.catalog_limited)summary.append(node('p','W obecnym katalogu nie ma już czarów dostępnych dla części twoich wyborów. Niewykorzystane wybory pozostają zachowane.','wizard-book-info'));}
  else if(mode==='book')summary.append(node('p','Czary z księgi przygotujesz do zwykłego rzucania. Znany rytuał możesz odprawić także bez przygotowania.'));
  else if(mode==='prepare')summary.append(node('p','Zaznacz zestaw na długi odpoczynek. Aktywne czary zmienią się dopiero po jego ukończeniu; przerwanie odpoczynku zachowuje obecny zestaw.'));
  else summary.append(node('p','Tutaj są sztuczki, zdolności oraz czary przygotowane do rzucania.'));
  parent.append(summary);const channel=p.character_sheet?.caster?.channel;if(mode!=='ready'&&channel?.key){const active=node('div',undefined,'caster-channel');active.append(node('strong',channel.name),node('small',`Pozostało ${Math.max(0,Math.ceil(channel.remaining||0))} s`),button('Przerwij',()=>h.send({type:'channel_cancel'})));parent.append(active);}if(mode==='prepare')preparation(parent,p,w,h,section);
 }
 function preparation(parent,p,w,h,section){const b=book(p),d=draft(p),box=node('section',undefined,'wizard-preparation');box.dataset.wizardPreparation='';
  const count=node('strong');count.dataset.wizardDraftCount='';box.append(count);
  const controls=node('div',undefined,'wizard-book-controls');const free=button('Dodaj do wolnych miejsc',()=>{const latest=h.state?.().player||p,packet=freePacket(latest);if(packet){free.disabled=true;h.send(packet);}});free.dataset.wizardFree='';controls.append(free);
  const long=button('Przygotuj i odpocznij',()=>{const latest=h.state?.()||{player:p,world:w},packet=restPacket(latest.player,latest.world,'long');if(packet){long.disabled=true;h.stop?.();h.send(packet);h.close?.();}});long.dataset.wizardLong='';controls.append(long,button('Przywróć obecny zestaw',()=>{const latest=h.state?.().player||p;draft(latest).prepared=new Set(book(latest)?.prepared||[]);h.refresh?.();}));box.append(controls);
  const reason=node('small');reason.dataset.wizardPreparationReason='';box.append(reason);parent.append(box);
  if(b.memorize_available){const memo=node('section',undefined,'wizard-memorize');memo.dataset.wizardMemorize='';memo.append(node('h3','Zapamiętanie czaru · poziom 5'),node('p','Po ukończeniu krótkiego odpoczynku zastąpisz jeden przygotowany czar innym z księgi. Liczba przygotowanych czarów pozostaje taka sama.'));
   const picks=node('div',undefined,'wizard-memorize-picks');for(const [key,label,ids]of [['forget','Zastąp przygotowany czar',b.prepared||[]],['prepare','Przygotuj czar z księgi',(b.known||[]).filter(id=>!b.prepared?.includes(id))]]){const field=node('label'),select=node('select');field.append(node('span',label));select.setAttribute('aria-label',label);select.dataset.wizardMemorizePick=key;select.append(new Option('Wybierz czar…',''));for(const id of ids)select.append(new Option(w.spells?.[id]?.name||id,id));if(ids.includes(d[key]))select.value=d[key];select.addEventListener('change',()=>{const latest=h.state?.().player||p;draft(latest)[key]=select.value;sync(parent,latest,h);});field.append(select);picks.append(field);}memo.append(picks);
   const short=button('Zapamiętaj i odpocznij',()=>{const latest=h.state?.()||{player:p,world:w},packet=restPacket(latest.player,latest.world,'short');if(packet){short.disabled=true;h.stop?.();h.send(packet);h.close?.();}});short.dataset.wizardShort='';memo.append(short);const explanation=node('small');explanation.dataset.wizardMemorizeReason='';memo.append(explanation);parent.append(memo);
  }else parent.append(node('p','Od poziomu 5: Zapamiętanie czaru pozwoli wymienić jeden czar po krótkim odpoczynku.','sheet-hint'));
  sync(parent,p,h);
 }
 function row(parent,p,s,h,section){const b=book(p),status=state(p,s);if(!b||!status)return;const mode=normalize(section),badge=node('small',status.prepared?'Przygotowany':status.known?'W księdze · nieprzygotowany':'Nieznany','wizard-spell-state');if(status.ritual&&!status.prepared)badge.textContent+=' · rytuał dostępny';parent.append(badge);
  if(mode==='learn'){const learn=button('Zapisz w księdze',()=>{const packet=learnPacket(h.state?.().player||p,s.id);if(packet){learn.disabled=true;h.send(packet);}},!learnPacket(p,s.id));learn.dataset.wizardLearn=s.id;learn.title=status.learnable?changeReason(p):'Ten czar nie jest dostępny dla twoich niewykorzystanych wyborów.';parent.append(learn);}
  if(mode==='prepare'){const d=draft(p),label=node('label',undefined,'wizard-spell-select'),check=node('input');check.type='checkbox';check.checked=d.prepared.has(s.id);check.dataset.wizardPrepared=s.id;check.setAttribute('aria-label','Przygotuj: '+s.name);check.addEventListener('change',()=>{const latest=h.state?.().player||p,current=draft(latest),latestBook=book(latest);if(!latestBook?.known?.includes(s.id))return;if(check.checked&&current.prepared.size<latestBook.prepared_limit)current.prepared.add(s.id);else current.prepared.delete(s.id);sync(h.content||parent,latest,h);});label.append(check,node('span','Przygotuj'));parent.append(label);}
 }
 function sync(parent,p,h){const b=book(p);if(!b)return;const d=draft(p),w=h.state?.().world||{},reason=changeReason(p,true),rest=root.BractwoRestUI?.model(p,w.rest_rules);
  for(const check of parent.querySelectorAll('[data-wizard-prepared]')){check.checked=d.prepared.has(check.dataset.wizardPrepared);check.disabled=!!reason||(!check.checked&&d.prepared.size>=b.prepared_limit);}
  for(const learn of parent.querySelectorAll('[data-wizard-learn]'))learn.disabled=!learnPacket(p,learn.dataset.wizardLearn);
  const count=parent.querySelector('[data-wizard-draft-count]');if(count)count.textContent=`Wybrany zestaw: ${d.prepared.size}/${b.prepared_limit}`;
  const free=parent.querySelector('[data-wizard-free]');if(free){free.hidden=!(b.free_preparations>0);free.disabled=!freePacket(p);free.textContent=`Dodaj do wolnych miejsc · ${b.free_preparations||0}`;}
  const long=parent.querySelector('[data-wizard-long]');if(long){long.disabled=!restPacket(p,w,'long');long.textContent=`Przygotuj i odpocznij · ${rest?.longSeconds||30} s`;}
  const text=parent.querySelector('[data-wizard-preparation-reason]');if(text)text.textContent=reason||rest?.longRestriction||(b.free_preparations>0?'Nowe wolne miejsca możesz uzupełnić od razu. Zamiana czarów wymaga długiego odpoczynku.':'Ruch, atak lub rozłączenie przerywa odpoczynek i anuluje zmianę zestawu.');
  const short=parent.querySelector('[data-wizard-short]');if(short){short.disabled=!restPacket(p,w,'short');short.textContent=`Zapamiętaj i odpocznij · ${rest?.shortSeconds||10} s`;}
  for(const select of parent.querySelectorAll('[data-wizard-memorize-pick]'))select.disabled=!!reason||!b.memorize_available;
  const memoText=parent.querySelector('[data-wizard-memorize-reason]');if(memoText)memoText.textContent=reason||rest?.shortRestriction||'Wybierz oba czary. Zmiana następuje wyłącznie po ukończeniu odpoczynku.';
 }
 const api={book,state,normalize,draft,changeReason,grantSummary,learnPacket,freePacket,restPacket,pending,sections,header,row,sync};root.BractwoWizardBookUI=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
